# Generated by Django 5.0 on 2023-12-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.CharField(
                choices=[
                    ("Dhaka", "Dhaka"),
                    ("Chittagong", "Chittagong"),
                    ("Dinajpur", "Dinajpur"),
                    ("Cumilla", "Cumilla"),
                    ("Faridpur", "Faridpur"),
                    ("Feni", "Feni"),
                    ("Habigang", "Habigang"),
                    ("Jamalpur", "Jamalpur"),
                    ("Jessore", "Jessore"),
                    ("Jhalakati", "Jhalakati"),
                    ("Khulna", "Khulna"),
                    ("Pabna", "Pabna"),
                    ("Panchagarh", "Panchagarh"),
                    ("Noakhali", "Noakhali"),
                    ("Dinajpur", "Dinajpur"),
                    ("Rangpur", "Rangpur"),
                    ("Sylhet", "Sylhet"),
                    ("Tangail", "Tangail"),
                ],
                max_length=51,
            ),
        ),
    ]
